_TMP_DIR = 'assets/tmp/'
_AUDIO_DIR = 'assets/audio/'
_ASSETS_DIR = 'assets/'
_DEEP_FRIED_FFMPEG_OPTIONS = '-v debug -y -af volume=5,bass=g=8,treble=g=-10'
_S3_ENDPOINT = 'https://s3.us-east-005.backblazeb2.com'
_ASSETS_BUCKET_NAME = 'Liberty-Files'
